matrix:
  include:
    - language: generic
      services:
        - docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose build
        - docker push ivanch/notify-web:latest
        - docker push ivanch/notify-api:latest
