language: generic
services:
  - docker

before_script:
  - docker pull ivanch/notificc:latest

script:
  - docker build -t ivanch/notificc:latest --build-arg PUBLIC_URL=http://localhost:8800 .

deploy:
  provider: script
  script: bash ./assets/deploy_dockerhub.sh
  on:
    branch: master