version: '3'
services:
  web:
    image: ivanch/notify-web
    ports:
        - "8800:80"
  api:
      image: ivanch/notify-api
      deploy:
        resources:
          limits:
            cpus: '0.1'
      ports:
          - "8810:8080"
      volumes:
          - api:/opt/api/shared

volumes:
  api: