version: '3'
services:
    web:
        image: joseivanchechen/notify-web
        ports:
            - "8000:80"
    api:
        image: joseivanchechen/notify-api
        ports:
              - "8080:8080"
        volumes:
              - api:/opt/api/shared

volumes:
    api: