version: '2.3'
services:
  api:
    image: ivanch/notificc-api
    build:
      context: ./api
      dockerfile: Dockerfile
      cache_from:
        - ivanch/notificc-api:latest
    cpus: 0.5
    mem_limit: 200M
    ports:
      - 8810:8080/tcp
    volumes:
      - api:/opt/api/shared:rw
  web:
    image: ivanch/notificc-web
    build:
      context: ./web
      dockerfile: Dockerfile
      cache_from:
        - ivanch/notificc-web:builder
        - ivanch/notificc-web:latest
    ports:
      - 8800:80/tcp
volumes:
  api: {}
