version: '2.3'
services:
  api:
    image: ivanch/notificc-api
    build:
      context: ./api
      dockerfile: Dockerfile
    cpus: 0.1
    mem_limit: 100M
    ports:
      - 8810:8080/tcp
    volumes:
      - api:/opt/api/shared:rw
    restart: unless-stopped
  web:
    image: ivanch/notificc-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8800:80/tcp
    restart: unless-stopped
volumes:
  api: {}
