version: '2.3'

services:
  ####
  # API Service
  ####
  api:
    image: ivanch/notificc-api
    build:
      context: ./api
    cpus: 0.1
    mem_limit: 100M
    ports:
      - ${API_PORT}:8080/tcp
    volumes:
      - api:/api/shared:rw
    restart: unless-stopped

  ####
  # Web Service
  ####
  web:
    image: ivanch/notificc-web
    build:
      context: ./web
      args:
        - PUBLIC_URL=${WEB_ENDPOINT}:${WEB_PORT}
        - API_URL=${API_ENDPOINT}:${API_PORT}
    ports:
      - ${WEB_PORT}:80/tcp
    restart: unless-stopped

volumes:
  api: {}
