name: Publish API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      working-directory: ./api
      run: |
        docker build -t ivanch/notify-api:latest .
    
    #- name: Publish Docker Image
    #  uses: elgohr/Publish-Docker-Github-Action@master
    #  with:
    #    name: ivanch/notify-api:latest
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
    #    workdir: ./api
